name: IaC Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tfsec:
    name: Terraform Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Scan tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          soft_fail: true